### ISSUE TITLE
Scrum Update 3: June 24th

### ISSUE THREAD

**Issue by vee-16** [cpsc455-bugstorm/TravelersTea#105]
**_Due: June 25th Sunday 2023 10pm_**

For all team members:

1. What did you work on this past iteration (2 weeks)?
2. What were any major issues/challenges you ran into?
3. What do you plan to work on for this coming iteration (2 weeks)?

~5 sentences max

**Comment by Graywing13** [comment]
Noreen Chan
CSID: s4v2b

1. What did you work on this past iteration (2 weeks)?

- Fix some ui bugs, add side panel for teacups view
- Do code reviews for other team members

2. What were any major issues/challenges you ran into?

- Hard to balance courseload with work

3. What do you plan to work on for this coming iteration (2 weeks)?

- Add compact view
- Add `/stages` endpoint

**Comment by AndyLiang1** [comment]
Andy Liang
CSID: v4e3b

What did you work on this past iteration (2 weeks)?

- Code reviews
- Explore JWT 

What were any major issues/challenges you ran into?

- Hard to balance course with work

What do you plan to work on for this coming iteration (2 weeks)?

- Add users end point 
- Add auth middleware

**Comment by vee-16** [comment]
Vaishnavi Sinha
CSID: h7b3p

What did you work on this past iteration (2 weeks)?

- Server: First draft for using google places API
- Frontend: Added routing for login screen and home page

What were any major issues/challenges you ran into?

- Wasn't able to complete more code reviews this sprint

What do you plan to work on for this coming iteration (2 weeks)?

- Continue improving backend models and controllers
- Perform more code reviews as compared to last sprint

**Comment by NLmeng** [comment]
Lymeng Naret
CSID: o2l3k

What did you work on this past iteration (2 weeks)?

- setting up thunks for trips
- write the backend (Create, Read, Update, Delete) for trips and connect it to frontend 

What were any major issues/challenges you ran into?

- decide on what pattern to use for backend and how to interact with it. ended up using Model/Router/Controller with thunks.

What do you plan to work on for this coming iteration (2 weeks)?

- work on frontend such as loading screen
- help with backend, if needed

**Comment by L0Lmaker** [comment]
Rithin Kumar Revur Suresh Kumar
CSID: m2i4v
What did you work on this past iteration (2 weeks)?

setting up openai function

Code reviews and design discussions

What were any major issues/challenges you ran into?

Nothing major

What do you plan to work on for this coming iteration (2 weeks)?

Connecting openai into backend

Backend endpoints
