### ISSUE TITLE
Scrum Update 4: July 15th

### ISSUE THREAD

**Issue by NLmeng** [cpsc455-bugstorm/TravelersTea#151]
**_Due: July 16th Sunday 2023 10pm_**

For all team members:

1. What did you work on this past iteration (2 weeks)?
2. What were any major issues/challenges you ran into?
3. What do you plan to work on for this coming iteration (2 weeks)?

~5 sentences max

**Comment by L0Lmaker** [comment]
Rithin Kumar Revur Suresh Kumar
CSID: m2i4v
What did you work on this past iteration (2 weeks)?

Edit Stage Frontend, Backend and OpenAI helper

Code reviews and design discussions

What were any major issues/challenges you ran into?

Nothing major

What do you plan to work on for this coming iteration (2 weeks)?

Finishing touches for MVP

**Comment by vee-16** [comment]
Vaishnavi Sinha
CSID: h7b3p

What did you work on this past iteration (2 weeks)?

- Integrated Google places API, added option to set org in Open API config
- Some code review

What were any major issues/challenges you ran into?

- Work school balance

What do you plan to work on for this coming iteration (2 weeks)?

- Continue improving minor bugs such as setting default trip name in sidebar to city name
- Work on app deployment

**Comment by NLmeng** [comment]
Lymeng Naret
CSID: o2l3k

What did you work on this past iteration (2 weeks)?

- made a loading screen and a high level controller for frontend
- help with backend, such as changes to model and connecting User's frontend and backend

What were any major issues/challenges you ran into?

- correctly control the frontend with redux thunks (fetch trips once in beginning, check if user is logged in, fetch stages only when trips are finished, etc.)

What do you plan to work on for this coming iteration (2 weeks)?

- work on stretch goals such as making Colloquial Prompts
- work on error/warning for frontend

**Comment by Graywing13** [comment]
Noreen Chan
CSID: s4v2b

What did you work on this past iteration (2 weeks)?

- Code reviews at the beginning
- Add stages thunks & integrate w/ FE

What were any major issues/challenges you ran into?

- Personal matters took up a lot of my energy and time

What do you plan to work on for this coming iteration (2 weeks)?

- UI improvements

**Comment by AndyLiang1** [comment]
Andy Liang
CSID: b4e3b

What did I do in the last 2 weeks: 
Code reviews 
Integrated BE all together (Trips, Open Ai, Google API)

Major Issues: 
Just managing time to work on project and work

What I plan to work on:
Creating a auth middleware 
End point for itinerary link
