### ISSUE TITLE
Center Globe on Screen

### ISSUE THREAD

**Issue by L0Lmaker** [cpsc455-bugstorm/TravelersTea#166]
Due to the Teacups, the Glob is slightly off center vertically. Picture for reference:
<img width="1512" alt="Screenshot 2023-07-15 at 9 39 40 AM" src="https://github.com/cpsc455-bugstorm/TravelersTea/assets/36722714/64c542ed-6e54-4bb2-a5ed-5c9b6de0c7b4">

**Comment by vee-16** [comment]
@L0Lmaker can we close this?

**Comment by L0Lmaker** [comment]
Ya
