### ISSUE TITLE
Create Codeowners file and lock pushes main branch 

### ISSUE THREAD

**Issue by L0Lmaker** [cpsc455-bugstorm/TravelersTea#2]

**Comment by vee-16** [comment]
Added the rule under main branch, this is completed now.
<img width="803" alt="Screenshot 2023-05-22 at 12 59 58 PM" src="https://github.com/cpsc455-bugstorm/TravelersTea/assets/59987667/84e2d133-51fd-45af-907f-2d81ca342717">
