### ISSUE TITLE
colloquial prompt opener slightly confusing

### ISSUE THREAD

**Issue by Graywing13** [cpsc455-bugstorm/TravelersTea#208]
![image](https://github.com/cpsc455-bugstorm/TravelersTea/assets/30674558/dd4685a2-db68-456b-bf2b-a749140acfa4)

**Comment by vee-16** [comment]
agreed on this, should we add a "Chat with GPT" or something simpler to understand before the arrow?

**Comment by Graywing13** [comment]
oh yeah that sounds good! another idea to combine w/ urs is to change the icon (e.g. 💬 )

I think it will be clear with these two together
