### ISSUE TITLE
When login/signup fails, user should get an alert

### ISSUE THREAD

**Issue by Graywing13** [cpsc455-bugstorm/TravelersTea#225]

**Comment by NLmeng** [comment]
i omitted error info related to auth on purpose. if you want to add it i think its fine to include it for sign up, but not for login for security reasons.

**Comment by Graywing13** [comment]
ah i see

had discord discussion that it's bad to tell em which part is incorrect, but it's ok to say "incorrect username or password" without specifying which one is wrong

so I'll write the PR and if it's still a issue, then we can just close the pr w/o merging

**Comment by Graywing13** [comment]
never mind it seems like you already added it in #223
