### ISSUE TITLE
Scrum Update 6: August 12th

### ISSUE THREAD

**Issue by vee-16** [cpsc455-bugstorm/TravelersTea#238]
Due: August 12th Sunday 2023 10pm

For all team members:

What did you work on this past iteration (2 weeks)?
What were any major issues/challenges you ran into?
What would you do if you were to continue the project?

~5 sentences max

**Comment by vee-16** [comment]
Vaishnavi Sinha
CSID: h7b3p

What did you work on this past iteration (2 weeks)?

- Final wrap up of project codebase, fix marker popups
- Code reviews

What were any major issues/challenges you ran into?

- Figuring out random errors thrown with Places API 

What would you do if you continues this project?

- Work on improving map markers so place details have information about closing time, reviews and directions to get there. 
- look into having beta testers for feedback on improvement

**Comment by L0Lmaker** [comment]
Rithin Kumar Revur Suresh Kumar
CSID: m2i4v

What did you work on this past iteration (2 weeks)?
- Share Trip Feature Integration
- Project Wrap up

What were any major issues/challenges you ran into?
- Demo preparation to get time down to exactly 7 minutes
- Share Itinerary auth management

What would you do if you were to continue the project?
- Switch out login to SSO  (google sign on)
- Business Model for a free tier and a paid tier
- Build out lucrative features for the paid tier 
  - no rate limiting
  - API connections to expedia or other travel agencies to book your travel

**Comment by NLmeng** [comment]
Lymeng Naret
CSID: o2l3k

What did you work on this past iteration (2 weeks)?
- add and tinker some settings to ratelimit middleware and proxy for production environment
- finding and fixing minor bugs such as padding on map, height of divs ...

What would you do if you were to continue the project?
- Make the app more robust especially the stylings in mobile
- Work on and improve the trip generating

**Comment by Graywing13** [comment]
Noreen Chan
CSID: s4v2b

What did you work on this past iteration (2 weeks)?
- Add light mode & mobile view
- Bug fixes: space background disappearing, scrollbar styling for consistency, view elements disappearing, sidebar showing up weird
- Vertical split mug ratings

What were any major issues/challenges you ran into?
- Mapbox sometimes tries to render nonexistent pixels through a chain of async calls that cannot be caught by try/catch. This happens especially often when switching the theme of the map. Needed to find alternative ways (useEffect, setting the map theme in other ways) to make the app robust to these errors.

What would you do if you continued this project?
- visual nits like how the markers don't fill up the right side when in noncompact trip view, and I think the details disappear when you switch to compact mode in the "shared trip" section

**Comment by AndyLiang1** [comment]
Andy Liang
CSID: b4e3b

What did you work on this past iteration (2 weeks)?

-Share Itinerary BE
-Auth test
-General app QA

What were any major issues/challenges you ran into?

-Finding time outside of co-op
-Testing was tedious

What would you do if you continues this project?

Create the table to display trips that are publicly shared and create a voting system.
