### ISSUE TITLE
Enforce Minimum 1 PR approval before merge  on the repo

### ISSUE THREAD

**Issue by L0Lmaker** [cpsc455-bugstorm/TravelersTea#3]

**Comment by NLmeng** [comment]
this has already been done
<img width="1710" alt="Screenshot 2023-05-21 at 2 13 53 PM" src="https://github.com/cpsc455-bugstorm/TravelersTea/assets/60766732/57db84ee-e4d2-4e5b-9aa1-150771a33eb0">

**Comment by vee-16** [comment]
Yes, as @NLmeng stated above. Closing this.
