### ISSUE TITLE
Scrum Update 1: May 27th

### ISSUE THREAD

**Issue by vee-16** [cpsc455-bugstorm/TravelersTea#43]
**_Due: 28th Sunday 2023 10pm_**

For all team members:

1. What did you work on this past iteration (2 weeks)?
2. What were any major issues/challenges you ran into?
3. What do you plan to work on for this coming iteration (2 weeks)?

~5 sentences max

**Comment by L0Lmaker** [comment]
Name: Rithin Kumar Revur Suresh Kumar
CSID: m2i4v

**1. What did you work on this past iteration (2 weeks)?**
* Began forming the prompting template for GPT API
* Code reviews for basic project setup

**2. What were any major issues/challenges you ran into?**
* Saying goodbye to TS

**3. What do you plan to work on for this coming iteration (2 weeks)?**
* Finish prompt template for GPT API
* setup backend calls for OpenAI

**Comment by AndyLiang1** [comment]
Andy Liang
CSID: b4e3b

**What did you work on this past iteration (2 weeks)?**

- Create basic backend to connect to Mongo Atlas Cluster
- Guided discussion for the backend architecture
- Created a backend workflow (Route -> Controller -> Model) for the User Entity (for users in our project)

**What were any major issues/challenges you ran into?**

-  Mainly using exports because JS exports are more complex than TS (module.exports vs export default). 

**What do you plan to work on for this coming iteration (2 weeks)?**

- Would like to help out in the front end and create some components.

**Comment by vee-16** [comment]
Vaishnavi Sinha
CSID: h7b3p

1. What did you work on this past iteration (2 weeks)?

- Helped set up the skeleton for project's Git org, repository, project board, and branch protection rules and sketch rough design
- Understanding and breaking down steps to use Google API for fetching place location & description information. 

2. What were any major issues/challenges you ran into?
- Challenge as a team was to evaluate which design pattern to proceed with for our backend setup.

3. What do you plan to work on for this coming iteration (2 weeks)?
- Implement Google API fetch calls and test with mock ChatGPT place suggestions.
- Continue evaluating UI designs for the project to present our information.

**Comment by Graywing13** [comment]
Name: Noreen Chan
CSID: s4v2b

1. What did you work on this past iteration (2 weeks)?

- Created basic frontend workflow in React & tailwind
- Drew out mocks, planned out site with team

2. What were any major issues/challenges you ran into?

- Hard to tell what flaws a design will have until you code it out (or make a mock), but both are time consuming. So just a lot of time to figure out how to make the app better. 

3. What do you plan to work on for this coming iteration (2 weeks)?

- Finish up frontend: make reusable, auto-populating timeline component
- Review other peoples' PRs

**Comment by NLmeng** [comment]
Name: Lymeng Naret
CSID: o2l3k

**1. What did you work on this past iteration (2 weeks)?**
* Wrote documentations for project progress 1, help setup the project such as adding linting and using yarn workspace, setup Redux, setup pre-commit and GitHub action.
* Code reviews

**2. What were any major issues/challenges you ran into?**
* nothing major, just getting on the same page as everyone

**3. What do you plan to work on for this coming iteration (2 weeks)?**
* Finish setting up pre-commit and GitHub action, create endpoint for Trip, and help with frontend
* More code reviews
