### ISSUE TITLE
Create Trip Endpoint

### ISSUE THREAD

**Issue by L0Lmaker** [cpsc455-bugstorm/TravelersTea#45]
The Create Trip Endpoint should accept a basic list of constraints:
* Destination
* Number of Days
* Budget
* Number of stages (frontend will refer to it as places per day, backend as stages)

For now it can respond with hardcoded data.

Work with the frontend folks to design a response structure that works for both frontend and backend.

Currently @L0Lmaker is working with the following structure:

```
const mongoose = require('mongoose')

const itineraryStageSchema = new mongoose.Schema({
  stage: Number,
  place: String,
  description: String,
  address: String,
  cost: Number,
})

const itinerarySchema = new mongoose.Schema({
  destination: String,
  budget: Number,
  days: Number,
  stages: Number,
  preferences: [String],
  plan: [itineraryStageSchema],
})

const Itinerary = mongoose.model('Itinerary', itinerarySchema)

module.exports = Itinerary

```

But it is open to changes if there needs to be any.

**Comment by NLmeng** [comment]
#94

**Comment by NLmeng** [comment]
#94
