### ISSUE TITLE
Scrum Update 2: June 10th

### ISSUE THREAD

**Issue by vee-16** [cpsc455-bugstorm/TravelersTea#73]
**_Due: June 11th Sunday 2023 10pm_**

For all team members:

1. What did you work on this past iteration (2 weeks)?
2. What were any major issues/challenges you ran into?
3. What do you plan to work on for this coming iteration (2 weeks)?

~5 sentences max

**Comment by vee-16** [comment]
Vaishnavi Sinha
CSID: h7b3p

1. What did you work on this past iteration (2 weeks)?

- Helped set up sign in/log out for user within our frontend 
- Helped improve code reusability with App.js and go through some PRs

2. What were any major issues/challenges you ran into?

- Challenge as a team was how to design the site and its components but we were able to convey our thoughts and collectively come to a decision on what the UI would look like

3. What do you plan to work on for this coming iteration (2 weeks)?

- Help with remaining frontend tasks (preference modes)
- Implement Google API fetch calls and test with mock ChatGPT place suggestions.

**Comment by Graywing13** [comment]
Noreen Chan
CSID: s4v2b

1. What did you work on this past iteration (2 weeks)?

- Redesign frontend to use horizontal teacups, make vertical timeline in day view
- Do code reviews for all other team members

2. What were any major issues/challenges you ran into?

- Hard to balance courseload with work

3. What do you plan to work on for this coming iteration (2 weeks)?

- Redesign trip view for better accessibility
- Discuss backend tasks with team members & do at least one of them

**Comment by L0Lmaker** [comment]
Rithin Kumar Revur Suresh Kumar
CSID: m2i4v

**What did you work on this past iteration (2 weeks)?**
1. Added updates to sidebar design and added dark theme accents
2. Made first draft of openai interface
3. Code reviews

**What were any major issues/challenges you ran into?**
Tough to manage coursework with a fulltime job, but having experience with these technologies has helped me significantly

**What do you plan to work on for this coming iteration (2 weeks)?**
1. Finalize Openai Interface
2. Work on creating and hooking up backend endpoints

**Comment by AndyLiang1** [comment]
Andy Liang
CSID: b4e3b

What did you work on this past iteration (2 weeks)?

- Implemented Map Component
- Code Reviews 

What were any major issues/challenges you ran into?

- Mapbox documentation was in pure html, css, js as opposed to React

What do you plan to work on for this coming iteration (2 weeks)?

- Create backend end points
- Figure out how to have shared postman tests

**Comment by NLmeng** [comment]
Lymeng Naret
CSID: o2l3k

What did you work on this past iteration (2 weeks)?

- finished setting up yarn workspace and update root instructions
- created a modal component, form component to create and edit trips
- code reviews such as helping out with Map's asynchrony and refactoring

What were any major issues/challenges you ran into?

- writing asynchronous codes cleanly and correctly (useCallback, useEffect)

What do you plan to work on for this coming iteration (2 weeks)?

- setting up thunks and help to improve the frontend
