### ISSUE TITLE
Make frontend 3.0

### ISSUE THREAD

**Issue by Graywing13** [cpsc455-bugstorm/TravelersTea#77]
![image](https://github.com/cpsc455-bugstorm/TravelersTea/assets/30674558/dff46934-8136-4c88-8d7e-933173876423)

- [ ] Build out regular view
- [ ] Build out compact view
- [ ] Remove this stuff in `viewSlice.js`: setContentFullscreen, setContentNonFullscreen,

**Comment by L0Lmaker** [comment]
Adding some more ideas discussed

**Comment by L0Lmaker** [comment]
* Mapbox themes
* Preference Modal (Maybe)
