### ISSUE TITLE
Code review work

### ISSUE THREAD

**Issue by Graywing13** [cpsc455-bugstorm/TravelersTea#82]
- [x] instead of blackGradient being a file, it should be a class in tailwind.config.js (Noreen did this)
- [x] should remove black gradient that covers screen in day view: 
- [x] After blue prince was added, some buttons are hard to see, please fix 

Images: 

![image](https://github.com/cpsc455-bugstorm/TravelersTea/assets/30674558/4052e175-e6e7-434a-99b0-083768676621)
![image](https://github.com/cpsc455-bugstorm/TravelersTea/assets/30674558/bab81055-d332-43de-b967-ac1536073c4e)

**Comment by NLmeng** [comment]
i think the buttons (in the sidebar) need to be more distinct, whether it is adding more opacity or box shadow or changing its color. personally, i think we should color contrast the border of the buttons with the background

**Comment by vee-16** [comment]
can we close this?

**Comment by Graywing13** [comment]
yes we can sorry for the late reply
