### ISSUE TITLE
Finalize endpoint structure

### ISSUE THREAD

**Issue by L0Lmaker** [cpsc455-bugstorm/TravelersTea#85]

**Comment by L0Lmaker** [comment]
`/users` @AndyLiang1 
* userID (email)

`/trips` @NLmeng #94 
* userID
* metada: preferences
* tripId

`/stages` @Graywing13 
* details about 1 place
* tripId that stage belongs to

**Comment by AndyLiang1** [comment]
I will deal with the users end point
