### ISSUE TITLE
Create Trip endpoints

### ISSUE THREAD

**Issue by NLmeng** [cpsc455-bugstorm/TravelersTea#94]
- [x] create: 
 - POST `/api/trips`
- [x] getAll: 
 - GET `/api/trips`
- [ ] get:
- GET `/api/trips/{id}`
- [x] edit: 
 - PATCH `/api/trips/{id}`
- [x] delete: 
 - DELETE `/api/trips/{id}`

(look into proper error handling etc.)

**Comment by NLmeng** [comment]
link #96 (create / edit / get all)

**Comment by NLmeng** [comment]
link #98 (delete)

**Comment by AndyLiang1** [comment]
@NLmeng i have error handling, i can show u my idea

**Comment by NLmeng** [comment]
most likely not going to need GET (single) `/api/trips/{id}`
