### ISSUE TITLE
Changes to Sidebar and TripEntry

### ISSUE THREAD

**Issue by NLmeng** [cpsc455-bugstorm/TravelersTea#99]
I changed Sidebar to use pixels instead of % because i think responsive sidebar is harder to manage the elements within it and it seems like most big websites have a fixed size sidebar until the screen gets really small. (i think it looks better this way)

I also changed the look / size of the elements in TripEntry to make it more visible.

**Comment by Graywing13** [comment]
Looks good, thanks for making the changes!

Some suggestions: 
![image](https://github.com/cpsc455-bugstorm/TravelersTea/assets/30674558/f8ad553d-4f07-4269-98f0-afc35f984724)
- Can we have more spacing between the icons?
- Can we truncate only if the icons are there?

**Comment by NLmeng** [comment]
given the width of the entry, i think more spaces between the icons would take too much space. do you think its too cramped?
now it truncate only if the icons are there

**Comment by Graywing13** [comment]
I see, yeah it'd be too cramped
Thx for the chances!

**Comment by NLmeng** [comment]
update: made the icons slightly smaller plus add a little spacing between:
<img width="249" alt="Screenshot 2023-06-18 at 12 50 45 PM" src="https://github.com/cpsc455-bugstorm/TravelersTea/assets/60766732/d6feeb6a-2fd3-4855-b1c5-88b92c670fee">

**Comment by L0Lmaker** [comment]
As a note for next time, can we tackle issues in seperate PRs if possible? hard to know which changes are related to which in a large PR

**Comment by NLmeng** [comment]
it was in a separate PR

**Comment by Graywing13** [comment]
Those icons look good!
